# Base settings used for linear morale parameter sweep
start_date = 2025-01-01
duration = 30
working_days = {'Tuesday', 'Friday', 'Wednesday', 'Monday', 'Thursday'}
strike_pattern = indefinite
weekly_escalation_start = 1
strike_pay_policy = fixed
strike_pay_rate = 0.5
dues_rate = 0.02
num_workers = 50
initial_wage = 30000.0
target_wage = 45000.0
initial_savings_range = (0.0, 5000.0)
initial_morale_range = (0.25, 1.0)
daily_expenditure_rate = 0.95
initial_employer_balance = 50000.0
initial_strike_fund = 50000.0
lab_size_n = 3
lab_size_prob = 0.5
total_friends_n = 3
total_friends_prob = 0.4
lab_friends_prob = 0.6
department_friends_prob = 0.3
university_friends_prob = 0.1
num_departments = 5
avg_department_size = 20
bargaining_committee_size = 10
steward_percentage = 0.2
branch_connectedness = 0.7
employer_network_file = EmoryEdgeList
union_network_file = None
morale_specification = linear
private_morale_alpha = 0.9
inflation = 0.05
belt_tightening = -0.1
sigmoid_gamma = 0.8
linear_alpha = 0.3
linear_beta = 0.3
linear_gamma = 0.4
linear_phi = 0.3
participation_threshold = 0.5
low_participation_threshold = 0.3
high_participation_threshold = 0.8
strike_pay_increase = 0.1
strike_pay_decrease = 0.05
min_strike_pay_rate = 0.3
max_strike_pay_rate = 0.8
monte_carlo_simulations = 100
